/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id:
    'us-east-2:3294ca33-47d9-4f83-bd52-53fddd145210',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_ROpcRkZ5v',
  aws_user_pools_web_client_id: 'd75ankl0gqrd0ki9mf2ng36m8',
  oauth: {
    domain: 'sigcomp-dev-np.auth.us-east-2.amazoncognito.com',
    scope: ['email', 'openid'],
    redirectSignIn: 'https://dashboard-staging.pmep.org/redirect',
    redirectSignOut: 'https://dashboard-staging.pmep.org/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS'
};

export default awsmobile;
