import {
  Grouping,
  NameGrouping,
  AnalyticsGrouping,
  UserGrouping,
  GoogleAuthUrl,
  UpsertTracking,
  CreateGrouping,
  CreateBulkUsersGrouping,
  BroadCastAppGrouping,
  DeleteDocument,
  CopyAssetS3,
  DeleteAssetS3Grouping,
  UpdateGrouping,
  UpdateGroupingStation,
  UpdateGroupingDistrict,
  UpdateGroupingSchool,
  UpdateGroupingClass,
  UpdateGroupingType,
  UpdateGroupingData,
  updateGroupingRename,
  UpdateGroupingTopology,
  UpdateGroupingDesc,
  UpdateGroupingState,
  UpdateGroupingAssetURLs,
  UpdateGroupingAvatarUrl,
  UpsertMMA,
  DeleteMMA,
  GroupingAdd,
  DocumentDelete,
  GroupingUpdate,
  PackageStation,
  UpdateMultiAssetStatus,
  IngestGoogle,
  TotalCount,
  MaterialsCount,
  StationGrouping,
  DistrictGrouping,
  SchoolGrouping,
  SchoolTermGrouping,
  ClassGrouping,
  MaterialGrouping,
  DeviceGrouping,
  GalleryGrouping,
  LibraryGrouping,
  TutorialGrouping,
  PackageGrouping,
  SDashPackageGrouping,
  BulkFilesGrouping,
  SysMessageGrouping,
  Grouping_grouping,
  TagGrouping,
  SysAdminGrouping,
  AdminGrouping,
  EducatorGrouping,
  StudentGrouping,
  CopyResourceToMaterial,
  MoveToNewParent,
  OnMoveToNewParent,
  OnUpsertMMA,
  OnDeleteMMA,
  UpdateGroupingList,
  canvasAuthUrl,
  IngestCanvas,
  CopyResource,
  CopySharedLesson,
  RestoreArchive,
  CreateRefGrouping,
  UpdateConfigApp,
  GetFolderSize,
  allStations,
  IngestSchoology,
  ArchiveClass
} from './Grouping.gql';

export default {
  queries: {
    grouping: Grouping,
    nameGrouping: NameGrouping,
    userGrouping: UserGrouping,
    analyticsGrouping: AnalyticsGrouping,
    googleAuthUrl: GoogleAuthUrl,
    totalCount: TotalCount,
    materialsCount: MaterialsCount,
    StationGrouping,
    DistrictGrouping,
    SchoolGrouping,
    SchoolTermGrouping,
    ClassGrouping,
    MaterialGrouping,
    GalleryGrouping,
    LibraryGrouping,
    TutorialGrouping,
    PackageGrouping,
    SDashPackageGrouping,
    BulkFilesGrouping,
    SysMessageGrouping,
    DeviceGrouping,
    BroadCastAppGrouping,
    tagGrouping: TagGrouping,
    SysAdminGrouping,
    AdminGrouping,
    EducatorGrouping,
    StudentGrouping,
    canvasAuthUrl,
    allStations
  },
  mutations: {
    createGrouping: CreateGrouping,
    createBulkUsersGrouping: CreateBulkUsersGrouping,
    deleteDocument: DeleteDocument,
    copyAssetS3: CopyAssetS3,
    deleteAssetS3Grouping: DeleteAssetS3Grouping,
    updateGrouping: UpdateGrouping,
    updateGroupingStation: UpdateGroupingStation,
    updateGroupingDistrict: UpdateGroupingDistrict,
    updateGroupingSchool: UpdateGroupingSchool,
    updateGroupingClass: UpdateGroupingClass,
    updateGroupingData: UpdateGroupingData,
    updateGroupingRename: updateGroupingRename,
    updateGroupingTopology: UpdateGroupingTopology,
    updateGroupingType: UpdateGroupingType,
    updateGroupingDesc: UpdateGroupingDesc,
    updateGroupingState: UpdateGroupingState,
    updateGroupingAssetURLs: UpdateGroupingAssetURLs,
    upsertMMA: UpsertMMA,
    deleteMMA: DeleteMMA,
    updateGroupingAvatarUrl: UpdateGroupingAvatarUrl,
    packageStation: PackageStation,
    updateMultiAssetStatus: UpdateMultiAssetStatus,
    upsertTracking: UpsertTracking,
    ingestGoogle: IngestGoogle,
    copyResourceToMaterial: CopyResourceToMaterial,
    MoveToNewParent,
    UpdateGroupingList,
    IngestCanvas,
    CopyResource,
    CopySharedLesson,
    restoreArchive: RestoreArchive,
    CreateRefGrouping,
    UpdateConfigApp,
    GetFolderSize,
    IngestSchoology,
    ArchiveClass
  },
  subscriptions: {
    groupingAdd: GroupingAdd,
    documentDelete: DocumentDelete,
    groupingUpdate: GroupingUpdate,
    onMoveToNewParent: OnMoveToNewParent,
    onUpsertMMA: OnUpsertMMA,
    onDeleteMMA: OnDeleteMMA
  },
  fragments: {
    Grouping_grouping
  }
};
